# Generated by Django 2.0.7 on 2018-07-24 13:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('object_id', models.UUIDField(editable=False)),
                ('delta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('serialized_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('content_type', models.ForeignKey(on_delete='CASCADE', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'histories',
                'ordering': ['-id'],
            },
        ),
    ]
