# Generated by Django 2.0.7 on 2018-07-24 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-id'], 'verbose_name_plural': 'histories'},
        ),
    ]
