# Generated by Django 2.0.7 on 2018-07-24 08:18

import common.models
from django.conf import settings
from django.db import migrations, models
import django_extensions.db.fields
import django_fsm
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', django_fsm.FSMField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'])),
                ('organization', models.ForeignKey(on_delete='CASCADE', to='crm.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'])),
                ('deliverable', models.ForeignKey(on_delete='CASCADE', related_name='facets', to='role_model.Deliverable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'])),
                ('description', models.TextField(max_length=1024)),
                ('deliverable', models.ForeignKey(on_delete='CASCADE', related_name='formats', to='role_model.Deliverable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'])),
                ('organization', models.ForeignKey(on_delete='CASCADE', to='crm.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operator', common.models.EnumField(max_length=64)),
                ('input_types', models.ManyToManyField(related_name='outputs', to='role_model.ContentType')),
                ('organization', models.ForeignKey(on_delete='CASCADE', to='crm.Organization')),
                ('output_type', models.ForeignKey(on_delete='CASCADE', related_name='inputs', to='role_model.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'])),
                ('group', models.ForeignKey(on_delete='CASCADE', related_name='roles', to='role_model.Group')),
                ('responsibilities', models.ManyToManyField(to='role_model.Responsibility')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contenttype',
            name='deliverable',
            field=models.ForeignKey(on_delete='CASCADE', related_name='content_types', to='role_model.Deliverable'),
        ),
        migrations.AddField(
            model_name='contenttype',
            name='facet',
            field=models.ForeignKey(on_delete='CASCADE', to='role_model.Facet'),
        ),
        migrations.AddField(
            model_name='contenttype',
            name='format',
            field=models.ForeignKey(on_delete='CASCADE', to='role_model.Format'),
        ),
        migrations.AddField(
            model_name='contenttype',
            name='group',
            field=models.ForeignKey(on_delete='CASCADE', to='role_model.Group'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='responsibility',
            field=models.ForeignKey(on_delete='CASCADE', to='role_model.Responsibility'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='role',
            field=models.ForeignKey(on_delete='CASCADE', to='role_model.Role'),
        ),
    ]
