# Generated by Django 2.0.7 on 2018-07-24 10:14

import common.models
from django.db import migrations
import django_fsm
import role_model.models


class Migration(migrations.Migration):

    dependencies = [
        ('role_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=django_fsm.FSMField(choices=[(role_model.models.Status('formal'), 'formal'), (role_model.models.Status('ad_hoc'), 'ad_hoc'), (role_model.models.Status('adjunct'), 'adjunct')], max_length=50),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='operator',
            field=common.models.EnumField(choices=[(role_model.models.Operator('transform'), 'transform'), (role_model.models.Operator('reduce'), 'reduce'), (role_model.models.Operator('sort'), 'sort'), (role_model.models.Operator('filter'), 'filter'), (role_model.models.Operator('combine'), 'combine')], max_length=64),
        ),
    ]
