# Generated by Django 2.0.7 on 2018-07-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role_model', '0002_auto_20180724_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsibility',
            options={'verbose_name_plural': 'responsibilities'},
        ),
    ]
